// Code generated by MockGen. DO NOT EDIT.
// Source: codex/internal/pkg/domain (interfaces: CollectionsUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	domain "codex/internal/pkg/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCollectionsUsecase is a mock of CollectionsUsecase interface.
type MockCollectionsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionsUsecaseMockRecorder
}

// MockCollectionsUsecaseMockRecorder is the mock recorder for MockCollectionsUsecase.
type MockCollectionsUsecaseMockRecorder struct {
	mock *MockCollectionsUsecase
}

// NewMockCollectionsUsecase creates a new mock instance.
func NewMockCollectionsUsecase(ctrl *gomock.Controller) *MockCollectionsUsecase {
	mock := &MockCollectionsUsecase{ctrl: ctrl}
	mock.recorder = &MockCollectionsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionsUsecase) EXPECT() *MockCollectionsUsecaseMockRecorder {
	return m.recorder
}

// GetCollection mocks base method.
func (m *MockCollectionsUsecase) GetCollection(arg0 uint64) (domain.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", arg0)
	ret0, _ := ret[0].(domain.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockCollectionsUsecaseMockRecorder) GetCollection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockCollectionsUsecase)(nil).GetCollection), arg0)
}

// GetFeed mocks base method.
func (m *MockCollectionsUsecase) GetFeed() (domain.FeedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed")
	ret0, _ := ret[0].(domain.FeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockCollectionsUsecaseMockRecorder) GetFeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockCollectionsUsecase)(nil).GetFeed))
}
