// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7bd5f161DecodeCodexInternalPkgDomain(in *jlexer.Lexer, out *BookmarkWithMovies) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.Id = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "imgSrc":
			out.Imgsrc = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7bd5f161EncodeCodexInternalPkgDomain(out *jwriter.Writer, in BookmarkWithMovies) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"imgSrc\":"
		out.RawString(prefix)
		out.String(string(in.Imgsrc))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BookmarkWithMovies) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7bd5f161EncodeCodexInternalPkgDomain(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BookmarkWithMovies) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7bd5f161DecodeCodexInternalPkgDomain(l, v)
}
func easyjson7bd5f161DecodeCodexInternalPkgDomain1(in *jlexer.Lexer, out *BookmarkResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.UserId = uint64(in.Uint64())
		case "bookmarksList":
			if in.IsNull() {
				in.Skip()
				out.Bookmarks = nil
			} else {
				in.Delim('[')
				if out.Bookmarks == nil {
					if !in.IsDelim(']') {
						out.Bookmarks = make([]Bookmark, 0, 1)
					} else {
						out.Bookmarks = []Bookmark{}
					}
				} else {
					out.Bookmarks = (out.Bookmarks)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Bookmark
					(v1).UnmarshalEasyJSON(in)
					out.Bookmarks = append(out.Bookmarks, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7bd5f161EncodeCodexInternalPkgDomain1(out *jwriter.Writer, in BookmarkResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.UserId))
	}
	{
		const prefix string = ",\"bookmarksList\":"
		out.RawString(prefix)
		if in.Bookmarks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Bookmarks {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BookmarkResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7bd5f161EncodeCodexInternalPkgDomain1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BookmarkResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7bd5f161DecodeCodexInternalPkgDomain1(l, v)
}
func easyjson7bd5f161DecodeCodexInternalPkgDomain2(in *jlexer.Lexer, out *Bookmark) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.Id = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "imgSrc":
			out.Imgsrc = string(in.String())
		case "public":
			out.Public = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7bd5f161EncodeCodexInternalPkgDomain2(out *jwriter.Writer, in Bookmark) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"imgSrc\":"
		out.RawString(prefix)
		out.String(string(in.Imgsrc))
	}
	{
		const prefix string = ",\"public\":"
		out.RawString(prefix)
		out.Bool(bool(in.Public))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Bookmark) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7bd5f161EncodeCodexInternalPkgDomain2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Bookmark) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7bd5f161DecodeCodexInternalPkgDomain2(l, v)
}
