DROP DATABASE IF EXISTS codex;

DROP ROLE IF EXISTS akino;

CREATE ROLE akino WITH PASSWORD '1234';

ALTER ROLE akino WITH LOGIN superuser;

CREATE DATABASE CoDex WITH OWNER = akino ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION
LIMIT
    = -1;